### ISSUE TITLE
Error navigating to settings page

### ISSUE THREAD

**Issue by cbarraford** [endpass/endpass-wallet#118]
I setup my local dev environment and created a wallet. When navigating to the settings page I got the following error. Maybe theres something wrong with my local dev environment, but since there isn't much for documentation, not sure if theres something else i need to configure/setup.

<img width="601" alt="screenshot 2018-08-01 09 49 34" src="https://user-images.githubusercontent.com/246180/43529159-453ddecc-9570-11e8-869b-374cb0d44aa3.png">

**Comment by kazurus** [comment]
This is a bug, thanks

**Comment by cbarraford** [comment]
I'll be opening a PR later today fixing this minor bug
